### PR TITLE
fix specifying both role-arn and principal-arn as command-line arguments fails with TypeError

### PR DESCRIPTION
**Pull request by Tantalon**
Fix for #149

```
  File "/usr/local/lib/python3.9/site-packages/awsume/awsumepy/app.py", line 132, in get_saml_credentials
    principal_plus_role_arn = ','.join(args.role_arn, args.principal_arn)
TypeError: str.join() takes exactly one argument (2 given)
```

This is the line of code, it's missing brackets:
`principal_plus_role_arn = ','.join(args.role_arn, args.principal_arn)`
should be:
`principal_plus_role_arn = ','.join([args.role_arn, args.principal_arn])`

### CODE REVIEW

**Comment by mbarneyjr** [comment]
Good catch! We'll try to merge this and include it along with #148 after we test it a little more internally

Thanks for the PR!

**Comment by Tantalon** [comment]
Hi @mbarneyjr, any update on the outstanding PRs?

**Comment by TheLandolorien** [comment]
I also ran into this issue and would like to resolve it for a SAML plugin I'm building. Though we probably need a unit test to validate this fully solves the issue.

**Comment by mtskillman** [comment]
cherry-picked the relevant commit and included into https://github.com/trek10inc/awsume/pull/224

**Pull request closed without merging**
