### PR TITLE
add support for session-name on cli

### PR DESCRIPTION
**Pull request by giuliocalzolari**
add support for session-name on cli

### CODE REVIEW

**Comment by giuliocalzolari** [comment]
@mbarneyjr

**Comment by giuliocalzolari** [comment]
h @mbarneyjr do you have update?

**Comment by felipe1982** [comment]
I don't understand the purpose of this PR. What extra functionality does it provide? What's the use case for it?

**Comment by giuliocalzolari** [comment]
when you perform a sts switch role you cannot specify the session name, in same use case is nice to set it for audit purpose.
only performing an sts:assumerole action the original username is preserved but if you do a sts:getsessiontoken in the destination account you only see the session name.

having the option to setup the session name with a custom string could be a nice feature

**Comment by mbarneyjr** [comment]
@giuliocalzolari I apologize for the late response, but I have just merged your changes, thanks for the PR!

**Pull request merged**
